version: '3.3'

services:
  tps:
    build: ./src/tps
    working_dir: /tps
    volumes:
      - ./src/tps:/tps
    ports:
      - ${TPS_PORT}:${TPS_PORT}
    networks:
      - localnet
  nginx:
    build: ./services/nginx
    volumes:
      - ./src/app-for-purchasing-service:/var/www/purchase-tps
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - purchase-tps
    networks:
      - localnet
  purchase-tps:
    build:
      context: ./services/purchase-tps
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./src/app-for-purchasing-service:/var/www/purchase-tps
      - ./services/purchase-tps/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres
    networks:
      - localnet
  postgres:
    build: ./services/postgres
    ports:
      - 54320:5432
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - localnet
  rabbit:
    build: ./services/rabbit
    ports:
      - 15672:15672
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
