version: '3.3'

services:
  tps: #topic predictor service
    build: ./src/tps
    working_dir: /tps
    volumes:
      - ./src/tps:/tps
    ports:
      - "5000:5000"
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
